name: System Tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: /home/runner/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install libsqlite3
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
      - name: Bundle install
        run: |
          bundle config path /home/runner/bundle
          bundle install --frozen
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Yarn install
        run: |
          yarn install
      - name: Run RSpec
        run: |
          bundle exec rails db:prepare
          bundle exec rails g anycable:download --bin-path=./bin
          bundle exec rails webpacker:compile
          ./bin/anycable-go --host "0.0.0.0" &
          export CABLE_URL="ws://$(hostname):8080/cable"
          bundle exec rspec --tag type:system
