name: Unit Tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: /home/runner/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install libsqlite3
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
      - name: Bundle install
        run: |
          bundle config path /home/runner/bundle
          bundle install --frozen
      - name: Run RSpec
        run: |
          bundle exec rails db:prepare
          bundle exec rspec --tag ~type:system
